index.html
=> Updated the index.html for TrustedFirmware.org

_config-production.yml, _config-staging.yml
=> Added Correct Themed Configuration Files

index.html
=> Content Changes to Trusted Firmware

css/responsive.css, css/style.css, index.html
=> Trusted Firmware about text updated.

.gitignore, index.html
FAQ details have been added to the TrustedFirmware.org landing site based on this [content](https://collaborate.linaro.org/display/ARM/Trusted+Firmware+Project+FAQ).
=> Added FAQ Content to the Trusted Firmware Landing Site

css/style.css, index.html
- Added the code section to the website
@bfletcher
=> Added the "Code" section to the TrustedFirmware.org website

index.html
Added the modified FAQ text requested by @bfletcher
=> Added updated FAQ text

_posts/2018-09-18-trusted-firmware-project-update.md
Single file blog post (no thumbnail needed) ideally for TF session later today at YVR18.
=> Blog post based on text from Matteo

_posts/2018-09-18-trusted-firmware-project-update.md
=> Updated the latest blog post title

_posts/2018-09-18-trusted-firmware-at-the-open-source-firmware-conference.md
…ence.md
Updates requested by Arm
=> Minor formatting updates based on feedback from Arm

_posts/2018-10-16-linaro-community-projects-division-announces-the-trusted-firmware-open-project.md
Added the new TrustedFirmware press release
=> Added the new TrustedFirmware press release

posts.json.html
Added the posts.json.html file which outputs JSON data containing details of all blog posts. This will be used in the Linaro.org/resources/ page where we will aggregate all blog posts from Linaro static sites and let users filter and search all of our resources.
=> Added the posts.json.html file which outputs JSON data containing details of all blog posts.

_pages/about/README.md
Text updates as requested by Shebu Varghese Kuriakose
=> Text updates as requested by Shebu Varghese Kuriakose

_pages/about/README.md
=> Text Update

README.md
=> Fix `serve` command

_data/nav.yml
=> Updating the OP-TEE blog

_data/nav.yml
=> Menu Item Title Corrected

_data/nav.yml
Removed 'docs' from navbar items
=> Removed 'docs' from navbar items

_posts/news/2019-10-21-linaro-transferring-op-tee-to-become-part-of-trusted-firmware.md
Replacing linked image with YouTube media embed 
Ref: #166
=> Replacing linked image with YouTube media embed

_posts/meetings/2019-11-13-tf-m-technical-forum.md
Somehow the tiny 100x25 GCal button gets expanded when rendered. Trying to fix the size.
=> Made calendar button size explicit

Gemfile, robots.txt
Robots.txt fix / Theme version bump
=> Robots.txt fix / Theme version bump

_authors/bill-fletcher.md, _authors/matteo-carlini.md, _authors/shebu-kuriakose.md, _authors/trusted-firmware.md
=> Author updates

_layouts/project.html
Added missing code link rendering. Updated responsive classes
=> Added missing code link rendering. Updated responsive classes

_layouts/project.html
=> Updated useful links style

_includes/tf_projects.html, _layouts/project.html, assets/css/app/custom.scss
Updated "Other Projects" Icons height / Center aligned projects on homepage / removed duplicated enquiries text
=> Updated "Other Projects" Icons height / Center aligned projects on homepage / removed duplicated enquiries text

_includes/components/jumbotron.html, _pages/cookies.md
Add missing /cookies/ page and fix broken link
=> Add missing /cookies/ page and fix broken link

Gemfile, _config.yml
Upgrading Jekyll theme version (Structured data fixes)
=> Upgrading Jekyll theme version (Structured data fixes)

404.html, _pages/404.md
=> Added missing 404 page

_data/nav.yml, _posts/blog/2020-07-22-tfm-v1-1-blog.md, _posts/blog/2020-11-30-tfm-v1-2-blog.md, _projects/tf-m.md
use the new build system paths instead of the old ones.
Reported-by: Karl Zhang <karl.zhang@arm.com>
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>
=> Update docs URL

_config.yml, _data/routingrules.json, _pages/security.md
Redirecting /security/ route to external url
=> Redirecting /security/ route to external url

_posts/blog/2018-09-18-trusted-firmware-at-the-open-source-firmware-conference.md
https://github.com/TrustedFirmwareWebsite/website/issues/175
=> Fixing broken link #175

_data/picture.yml, _includes/blog/post_sidebar.html, _posts/blog/2018-09-18-trusted-firmware-at-the-open-source-firmware-conference.md, assets/js/app/main.js, assets/json/posts.json, assets/json/recentPosts.json
Updating other posts section to use Javascript
=> Updating other posts section to use Javascript

_data/members.json, _includes/members.html
=> Temporarily removing .ru link

_projects/tf-a.md, _projects/tf-m.md
Making names consistent here and in github organization repos
=> Minor cleanup 

src/content/pages/faq.md
=> Fix search engine query syntax

.github/workflows/pullrequest.yml, .github/workflows/push.yml, CODEOWNERS
The additional section has an `if` check because the workflow has to be updated to `main` before the secondary PR to add the dashboard will build.
=> Add new section to build dashboard data
